# Generated by Django 3.2.16 on 2023-05-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230516_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
